name = "ollema"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.3.6 and < 5.0.0"
lustre_ssg = ">= 0.8.1 and < 1.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
tom = ">= 1.0.1 and < 2.0.0"
